<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace d3acc\models\base;

use Yii;


/**
 * This is the base-model class for table "ac_account".
 *
 * @property integer $id
 * @property integer $sys_company_id
 * @property string $code
 * @property string $name
 *
 * @property \d3acc\models\AcDef[] $acDefs
 * @property \d3acc\models\AcPeriodBalanceDim[] $acPeriodBalanceDims
 * @property \d3acc\models\AcRecAcc[] $acRecAccs
 * @property string $aliasModel
 */
abstract class AcAccount extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName(): string
    {
        return 'ac_account';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            'required' => [['code', 'name'], 'required'],
            'smallint Unsigned' => [['id','sys_company_id'],'integer' ,'min' => 0 ,'max' => 65535],
            [['code'], 'string', 'max' => 10],
            [['name'], 'string', 'max' => 50]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('d3acc', 'ID'),
            'sys_company_id' => Yii::t('d3acc', 'Sys Company ID'),
            'code' => Yii::t('d3acc', 'Code'),
            'name' => Yii::t('d3acc', 'Name'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints(): array
    {
        return array_merge(parent::attributeHints(), [
            'code' => Yii::t('d3acc', 'Code'),
            'name' => Yii::t('d3acc', 'Name'),
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAcDefs()
    {
        return $this->hasMany(\d3acc\models\AcDef::className(), ['account_id' => 'id'])->inverseOf('account');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAcPeriodBalanceDims()
    {
        return $this->hasMany(\d3acc\models\AcPeriodBalanceDim::className(), ['account_id' => 'id'])->inverseOf('account');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAcRecAccs()
    {
        return $this->hasMany(\d3acc\models\AcRecAcc::className(), ['account_id' => 'id'])->inverseOf('account');
    }




}
