<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace d3acc\models\base;

use Yii;


/**
 * This is the base-model class for table "ac_dim_group".
 *
 * @property integer $id
 * @property integer $sys_company_id
 * @property string $name
 *
 * @property \d3acc\models\AcDim[] $acDims
 * @property string $aliasModel
 */
abstract class AcDimGroup extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName(): string
    {
        return 'ac_dim_group';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            'required' => [['name'], 'required'],
            'smallint Unsigned' => [['id','sys_company_id'],'integer' ,'min' => 0 ,'max' => 65535],
            [['name'], 'string', 'max' => 50]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('d3acc', 'ID'),
            'sys_company_id' => Yii::t('d3acc', 'Sys Company ID'),
            'name' => Yii::t('d3acc', 'Name'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints(): array
    {
        return array_merge(parent::attributeHints(), [
            'name' => Yii::t('d3acc', 'Name'),
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAcDims()
    {
        return $this->hasMany(\d3acc\models\AcDim::className(), ['group_id' => 'id']);
    }

}
