<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace d3acc\models\base;

use Yii;
use yii\db\Exception;

/**
 * This is the base-model class for table "ac_dim".
 *
 * @property integer $id
 * @property integer $group_id
 * @property string $name
 *
 * @property \d3acc\models\AcDimGroup $group
 * @property \d3acc\models\AcTranDim[] $acTranDims
 * @property string $aliasModel
 */
abstract class AcDim extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ac_dim';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['group_id', 'name'], 'required'],
            [['group_id'], 'integer'],
            [['name'], 'string', 'max' => 50],
            [['group_id'], 'exist', 'skipOnError' => true, 'targetClass' => \d3acc\models\AcDimGroup::className(), 'targetAttribute' => ['group_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('d3acc', 'ID'),
            'group_id' => Yii::t('d3acc', 'Ac_dim_group'),
            'name' => Yii::t('d3acc', 'Name'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'group_id' => Yii::t('d3acc', 'Ac_dim_group'),
            'name' => Yii::t('d3acc', 'Name'),
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getGroup()
    {
        return $this->hasOne(\d3acc\models\AcDimGroup::className(), ['id' => 'group_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAcTranDims()
    {
        return $this->hasMany(\d3acc\models\AcTranDim::className(), ['dim_id' => 'id']);
    }


    /**
     * @return \d3acc\models\AcTranDim     */
    public function newAcTranDims()
    {
        if ($this->getIsNewRecord()){
            throw new Exception('Can not create new related record for new record!');
        }
        $model = new \d3acc\models\AcTranDim();
        $model->dim_id = $this->id;
        return $model;
    }



    public function saveOrException($runValidation = true, $attributeNames = null)
    {
        if(!parent::save($runValidation, $attributeNames)){
            throw new Exception(json_encode($this->getErrors()));
        }
    }
}
