<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace d3acc\models\base;

use Yii;

/**
 * This is the base-model class for table "ac_period".
 *
 * @property integer $id
 * @property integer $period_type
 * @property string $from
 * @property string $to
 * @property string $status
 *
 * @property \d3acc\models\AcTran[] $acTrans
 * @property string $aliasModel
 */
abstract class AcPeriod extends \yii\db\ActiveRecord
{



    /**
    * ENUM field values
    */
    const STATUS_PLANNED = 'Planned';
    const STATUS_ACTIVE = 'Active';
    const STATUS_CLOSED = 'Closed';
    var $enum_labels = false;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ac_period';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['period_type', 'from', 'to'], 'required'],
            [['period_type'], 'integer'],
            [['from', 'to'], 'safe'],
            [['status'], 'string'],
            ['status', 'in', 'range' => [
                    self::STATUS_PLANNED,
                    self::STATUS_ACTIVE,
                    self::STATUS_CLOSED,
                ]
            ]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('poker', 'ID'),
            'period_type' => Yii::t('poker', 'Type'),
            'from' => Yii::t('poker', 'From'),
            'to' => Yii::t('poker', 'To'),
            'status' => Yii::t('poker', 'Status'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'period_type' => Yii::t('poker', 'Type'),
            'from' => Yii::t('poker', 'From'),
            'to' => Yii::t('poker', 'To'),
            'status' => Yii::t('poker', 'Status'),
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAcTrans()
    {
        return $this->hasMany(\d3acc\models\AcTran::className(), ['period_id' => 'id'])->inverseOf('period');
    }




    /**
     * get column status enum value label
     * @param string $value
     * @return string
     */
    public static function getStatusValueLabel($value){
        $labels = self::optsStatus();
        if(isset($labels[$value])){
            return $labels[$value];
        }
        return $value;
    }

    /**
     * column status ENUM value labels
     * @return array
     */
    public static function optsStatus()
    {
        return [
            self::STATUS_PLANNED => Yii::t('poker', self::STATUS_PLANNED),
            self::STATUS_ACTIVE => Yii::t('poker', self::STATUS_ACTIVE),
            self::STATUS_CLOSED => Yii::t('poker', self::STATUS_CLOSED),
        ];
    }

}
