<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace d3acc\models\base;

use Yii;
use d3acc\models\AcPeriod;
use d3acc\models\AcRecAcc;
use yii\db\ActiveQuery;
use yii\db\ActiveRecord;

/**
 * This is the base-model class for table "ac_period_balance".
 *
 * @property integer $id
 * @property integer $sys_company_id
 * @property integer $period_id
 * @property integer $rec_acc_id
 * @property float $amount
 *
 * @property AcPeriod $period
 * @property AcRecAcc $recAcc
 * @property string $aliasModel
 */
abstract class AcPeriodBalance extends ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName(): string
    {
        return 'ac_period_balance';
    }

    /**
     * @inheritdoc
     */
    public function rules(): array
    {
        return [
            'required' => [['period_id', 'rec_acc_id', 'amount'], 'required'],
            'decimal-signed-12-2' => [
                ['amount'],
                    'number',
                    'numberPattern' => '/^([\+-]?((\d{1,10})|(\d{0,10}\.\d{0,2})|(\.\d{1,2})))$/',
                    'message' =>  Yii::t('crud', 'Invalid number format')
                ],
            'smallint Unsigned' => [['sys_company_id','period_id'],'integer' ,'min' => 0 ,'max' => 65535],
            'integer Unsigned' => [['id','rec_acc_id'],'integer' ,'min' => 0 ,'max' => 4294967295],
            [['amount'], 'number'],
            [['period_id'], 'exist', 'skipOnError' => true, 'targetClass' => AcPeriod::class, 'targetAttribute' => ['period_id' => 'id']],
            [['rec_acc_id'], 'exist', 'skipOnError' => true, 'targetClass' => AcRecAcc::class, 'targetAttribute' => ['rec_acc_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels(): array
    {
        return [
            'id' => Yii::t('d3acc', 'ID'),
            'sys_company_id' => Yii::t('d3acc', 'Sys Company ID'),
            'period_id' => Yii::t('d3acc', 'Period'),
            'rec_acc_id' => Yii::t('d3acc', 'Account'),
            'amount' => Yii::t('d3acc', 'Amount'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints(): array
    {
        return array_merge(parent::attributeHints(), [
            'period_id' => Yii::t('d3acc', 'Period'),
            'rec_acc_id' => Yii::t('d3acc', 'Account'),
            'amount' => Yii::t('d3acc', 'Amount'),
        ]);
    }

    /**
     * @return ActiveQuery
     */
    public function getPeriod(): ActiveQuery
    {
        return $this
            ->hasOne(AcPeriod::class, ['id' => 'period_id'])
            ->inverseOf('acPeriodBalances');
    }

    /**
     * @return ActiveQuery
     */
    public function getRecAcc(): ActiveQuery
    {
        return $this
            ->hasOne(AcRecAcc::class, ['id' => 'rec_acc_id'])
            ->inverseOf('acPeriodBalances');
    }

}
