<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace d3acc\models\base;

use Yii;
use yii\db\Exception;

/**
 * This is the base-model class for table "ac_period_balance_dim".
 *
 * @property integer $id
 * @property integer $period_id
 * @property integer $dim_id
 * @property string $amount
 *
 * @property \d3acc\models\AcDim $dim
 * @property \d3acc\models\AcPeriod $period
 * @property string $aliasModel
 */
abstract class AcPeriodBalanceDim extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ac_period_balance_dim';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['period_id', 'dim_id', 'amount'], 'required'],
            [['period_id', 'dim_id'], 'integer'],
            [['amount'], 'number'],
            [['dim_id'], 'exist', 'skipOnError' => true, 'targetClass' => \d3acc\models\AcDim::className(), 'targetAttribute' => ['dim_id' => 'id']],
            [['period_id'], 'exist', 'skipOnError' => true, 'targetClass' => \d3acc\models\AcPeriod::className(), 'targetAttribute' => ['period_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('d3acc', 'ID'),
            'period_id' => Yii::t('d3acc', 'Period'),
            'dim_id' => Yii::t('d3acc', 'Dimension'),
            'amount' => Yii::t('d3acc', 'Amount'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'period_id' => Yii::t('d3acc', 'Period'),
            'dim_id' => Yii::t('d3acc', 'Dimension'),
            'amount' => Yii::t('d3acc', 'Amount'),
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDim()
    {
        return $this->hasOne(\d3acc\models\AcDim::className(), ['id' => 'dim_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPeriod()
    {
        return $this->hasOne(\d3acc\models\AcPeriod::className(), ['id' => 'period_id']);
    }




    public function saveOrException($runValidation = true, $attributeNames = null)
    {
        if(!parent::save($runValidation, $attributeNames)){
            throw new Exception(json_encode($this->getErrors()));
        }
    }
}
