<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace d3acc\models\base;

use Yii;
use yii\db\ActiveQuery;
use yii\db\ActiveRecord;

/**
 * This is the base-model class for table "ac_rec_acc".
 *
 * @property integer $id
 * @property integer $sys_company_id
 * @property integer $account_id
 * @property integer $currency_id
 * @property string $label
 *
 * @property \d3acc\models\AcPeriodBalance[] $acPeriodBalances
 * @property \d3acc\models\AcRecRef[] $acRecRefs
 * @property \d3acc\models\AcTran[] $acTrans
 * @property \d3acc\models\AcTran[] $acTrans0
 * @property \d3acc\models\AcAccount $account
 * @property string $aliasModel
 */
abstract class AcRecAcc extends ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName(): string
    {
        return 'ac_rec_acc';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            'required' => [['account_id'], 'required'],
            'tinyint Unsigned' => [['currency_id'],'integer' ,'min' => 0 ,'max' => 255],
            'smallint Unsigned' => [['id','sys_company_id','account_id'],'integer' ,'min' => 0 ,'max' => 65535],
            [['label'], 'string', 'max' => 100],
            [['account_id'], 'exist', 'skipOnError' => true, 'targetClass' => \d3acc\models\AcAccount::class, 'targetAttribute' => ['account_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('d3acc', 'ID'),
            'sys_company_id' => Yii::t('d3acc', 'Sys Company ID'),
            'account_id' => Yii::t('d3acc', 'Account'),
            'currency_id' => Yii::t('d3acc', 'Currency'),
            'label' => Yii::t('d3acc', 'Label'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints(): array
    {
        return array_merge(parent::attributeHints(), [
            'account_id' => Yii::t('d3acc', 'Account'),
            'label' => Yii::t('d3acc', 'Label'),
        ]);
    }

    /**
     * @return ActiveQuery
     */
    public function getAcPeriodBalances()
    {
        return $this->hasMany(\d3acc\models\AcPeriodBalance::class, ['rec_acc_id' => 'id'])->inverseOf('recAcc');
    }

    /**
     * @return ActiveQuery
     */
    public function getAcRecRefs()
    {
        return $this->hasMany(\d3acc\models\AcRecRef::class, ['rec_account_id' => 'id'])->inverseOf('recAccount');
    }

    /**
     * @return ActiveQuery
     */
    public function getAcTrans()
    {
        return $this->hasMany(\d3acc\models\AcTran::class, ['debit_rec_acc_id' => 'id'])->inverseOf('debitRecAcc');
    }

    /**
     * @return ActiveQuery
     */
    public function getAcTrans0()
    {
        return $this->hasMany(\d3acc\models\AcTran::class, ['credit_rec_acc_id' => 'id'])->inverseOf('creditRecAcc');
    }

    /**
     * @return ActiveQuery
     */
    public function getAccount()
    {
        return $this->hasOne(\d3acc\models\AcAccount::class, ['id' => 'account_id'])->inverseOf('acRecAccs');
    }



}
