<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace d3acc\models\base;

use Yii;
use d3acc\models\AcDef;
use d3acc\models\AcRecAcc;
use yii\db\ActiveQuery;
use yii\db\ActiveRecord;

/**
 * This is the base-model class for table "ac_rec_ref".
 *
 * @property integer $id
 * @property integer $sys_company_id
 * @property integer $def_id
 * @property integer $rec_account_id
 * @property string $pk_value
 *
 * @property AcDef $def
 * @property AcRecAcc $recAccount
 * @property string $aliasModel
 */
abstract class AcRecRef extends ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName(): string
    {
        return 'ac_rec_ref';
    }

    /**
     * @inheritdoc
     */
    public function rules(): array
    {
        return [
            'required' => [['def_id', 'rec_account_id', 'pk_value'], 'required'],
            'smallint Unsigned' => [['sys_company_id','def_id'],'integer' ,'min' => 0 ,'max' => 65535],
            'integer Unsigned' => [['id','rec_account_id'],'integer' ,'min' => 0 ,'max' => 4294967295],
            'bigint Unsigned' => [['pk_value'],'integer' ,'min' => 0 ,'max' => 1.844674407371E+19],
            [['def_id'], 'exist', 'skipOnError' => true, 'targetClass' => AcDef::class, 'targetAttribute' => ['def_id' => 'id']],
            [['rec_account_id'], 'exist', 'skipOnError' => true, 'targetClass' => AcRecAcc::class, 'targetAttribute' => ['rec_account_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels(): array
    {
        return [
            'id' => Yii::t('d3acc', 'ID'),
            'sys_company_id' => Yii::t('d3acc', 'Sys Company ID'),
            'def_id' => Yii::t('d3acc', 'Def ID'),
            'rec_account_id' => Yii::t('d3acc', 'Rec Account ID'),
            'pk_value' => Yii::t('d3acc', 'Pk Value'),
        ];
    }

    /**
     * @return ActiveQuery
     */
    public function getDef(): ActiveQuery
    {
        return $this
            ->hasOne(AcDef::class, ['id' => 'def_id'])
            ->inverseOf('acRecRefs');
    }

    /**
     * @return ActiveQuery
     */
    public function getRecAccount(): ActiveQuery
    {
        return $this
            ->hasOne(AcRecAcc::class, ['id' => 'rec_account_id'])
            ->inverseOf('acRecRefs');
    }

}
