<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace d3acc\models\base;

use Yii;
use yii\db\ActiveRecord;

/**
 * This is the base-model class for table "ac_rec_table".
 *
 * @property integer $id
 * @property string $name
 * @property string $aliasModel
 */
abstract class AcRecTable extends ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName(): string
    {
        return 'ac_rec_table';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            'required' => [['name'], 'required'],
            'integer Unsigned' => [['id'],'integer' ,'min' => 0 ,'max' => 4294967295],
            [['name'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('d3acc', 'ID'),
            'name' => Yii::t('d3acc', 'Name'),
        ];
    }



}
